# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  pull_request:
    branches: [master, dev, v2]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: staging

    env: VUE_APP_ANALYTICS_UA=${{ secrets.VUE_APP_ANALYTICS_UA }}
      VUE_APP_GRAPHQL_URL=${{ secrets.VUE_APP_GRAPHQL_URL }}
      VUE_APP_ENABLE_STATS=${{ secrets.VUE_APP_ENABLE_STATS }}
      MONGOBD_URI=${{ secrets.MONGOBD_URI }}
      MONGODB_DB=${{ secrets.MONGODB_DB }}
      MONGODB_USER=${{ secrets.MONGODB_USER }}
      MONGOBD_PASS=${{ secrets.MONGOBD_PASS }}
      GQL_INTROSPECTION=${{ secrets.GQL_INTROSPECTION }}
      GQL_PLAYGROUND=${{ secrets.GQL_PLAYGROUND }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.19.0'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Dependencies
        run: yarn

      - name: Linting
        run: yarn lint

      - name: Unit Tests
        run: yarn test:unit

      - name: e2e Tests
        run: yarn test:e2e
